create table agent_groups
(
    agent_group_id          varchar(255)                not null
        primary key,
    agent_group_name        varchar(255)                not null,
    agent_group_description varchar(2000),
    active                  boolean default false       not null,
    reg_user_id             varchar(255),
    reg_date_time           timestamp(6) with time zone not null,
    mod_user_id             varchar(255),
    mod_date_time           timestamp(6) with time zone not null
);

create table agent_groups_agents
(
    agent_group_id varchar(255) not null
        references agent_groups,
    order_idx      integer      not null,
    ip             varchar(255),
    user_name      varchar(255),
    primary key (agent_group_id, order_idx)
);

create table agent_groups_tags
(
    agent_group_id varchar(255) not null
        references agent_groups,
    tag_value      varchar(255)
);

create table jobs
(
    job_id          varchar(255)         not null
        primary key,
    job_name        varchar(255)         not null,
    job_description varchar(2000),
    job_type        varchar(255)         not null,
    active          boolean default true not null,
    period          varchar(255),
    script          text
);

create table jobs_target_agents
(
    job_id            varchar(255) not null
        references jobs,
    order_idx         integer      not null,
    target_agent_type varchar(255),
    agent_group_id    varchar(255),
    ip                varchar(255),
    user_name         varchar(255),
    primary key (job_id, order_idx)
);

create table job_executions
(
    job_execution_id     varchar(255) not null
        primary key,
    job_id               varchar(255) not null,
    job_execution_no     bigint       not null,
    job_history_no       bigint       not null,
    job_execution_status varchar(255) not null,
    execution_user_id    varchar(255),
    execution_date_time  timestamp(6) with time zone,
    start_date_time      timestamp(6) with time zone,
    end_date_time        timestamp(6) with time zone,
    constraint uidx_job_id_job_execution_no
        unique (job_id, job_execution_no)
);

create table job_executions_target_agents
(
    job_execution_id                  varchar(255) not null
        references job_executions,
    order_idx                         integer      not null,
    ip                                varchar(255) not null,
    user_name                         varchar(255) not null,
    agent_group_id                    varchar(255),
    job_execution_target_agent_status varchar(255),
    start_date_time                   timestamp(6) with time zone,
    end_date_time                     timestamp(6) with time zone,
    log                               text,
    primary key (job_execution_id, order_idx)
);

create table job_history
(
    seq            bigint generated by default as identity
        primary key,
    job_id         varchar(255)                not null,
    job_history_no bigint                      not null,
    job_name       varchar(255)                not null,
    job_type       varchar(255)                not null,
    history        text,
    reg_user_id    varchar(255),
    reg_date_time  timestamp(6) with time zone not null,
    constraint uidx_job_id_job_history_no
        unique (job_id, job_history_no)
);
