create table public.agent_groups
(
    agent_group_id          varchar(100)                not null
        primary key,
    active                  boolean default false       not null,
    agent_group_description varchar(1000),
    agent_group_name        varchar(100)                not null,
    mod_date_time           timestamp(6) with time zone not null,
    mod_user_id             varchar(100),
    reg_date_time           timestamp(6) with time zone not null,
    reg_user_id             varchar(100)
);

create table public.agent_groups_agents
(
    agent_group_id varchar(100) not null
        constraint fkr6hc4qth95i2ny4xlp0eoy53b
            references public.agent_groups,
    ip             varchar(255),
    user_name      varchar(255),
    order_idx      integer      not null,
    primary key (agent_group_id, order_idx)
);

create table public.agent_groups_tags
(
    agent_group_id varchar(100) not null
        constraint fki860dwcalc421lsxaxj5d30gs
            references public.agent_groups,
    tags           varchar(255)
);

create table public.job_executions
(
    job_execution_id    varchar(255) not null
        primary key,
    end_date_time       timestamp(6) with time zone,
    execution_date_time timestamp(6) with time zone,
    execution_user_id   varchar(100),
    job_execution_no    bigint       not null,
    job_history_no      bigint       not null,
    job_id              varchar(255) not null,
    job_status          varchar(100) not null
        constraint job_executions_job_status_check
            check ((job_status)::text = ANY
                   ((ARRAY ['CREATED'::character varying, 'READY'::character varying, 'STARTED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'STOPPED'::character varying, 'SKIPPED'::character varying])::text[])),
    start_date_time     timestamp(6) with time zone,
    constraint uk8ji475i4d5xc8oecn5bp5vf6j
        unique (job_id, job_execution_no)
);

create table public.job_executions_target_agents
(
    job_execution_id varchar(255) not null
        constraint fk9p0ekhongqwl9kvbe7c8yxbln
            references public.job_executions,
    agent_group_id   varchar(200),
    ip               varchar(200) not null,
    user_name        varchar(200) not null,
    end_date_time    timestamp(6) with time zone,
    log              text,
    start_date_time  timestamp(6) with time zone,
    status           smallint
        constraint job_executions_target_agents_status_check
            check ((status >= 0) AND (status <= 5)),
    order_idx        integer      not null,
    primary key (job_execution_id, order_idx)
);

create table public.job_history
(
    seq            bigint generated by default as identity
        primary key,
    history        text,
    job_history_no bigint                      not null,
    job_id         varchar(255)                not null,
    job_name       varchar(100)                not null,
    job_type       varchar(255)                not null
        constraint job_history_job_type_check
            check ((job_type)::text = 'SSH'::text),
    reg_date_time  timestamp(6) with time zone not null,
    reg_user_id    varchar(100),
    constraint ukc70mxeo0ruxkd7993fgsat889
        unique (job_id, job_history_no)
);

create table public.jobs
(
    job_id          varchar(255)         not null
        primary key,
    active          boolean default true not null,
    job_description varchar(1000),
    job_name        varchar(100)         not null,
    job_type        varchar(255)
        constraint jobs_job_type_check
            check ((job_type)::text = 'SSH'::text),
    period          varchar(100),
    script          text
);

create table public.jobs_target_agents
(
    job_id            varchar(255) not null
        constraint fk2ajbhnf84v775o59xwot9k83c
            references public.jobs,
    agent_group_id    varchar(100),
    ip                varchar(100),
    target_agent_type varchar(100)
        constraint jobs_target_agents_target_agent_type_check
            check ((target_agent_type)::text = ANY
                   ((ARRAY ['GROUP'::character varying, 'AGENT'::character varying])::text[])),
    user_name         varchar(100),
    order_idx         integer      not null,
    primary key (job_id, order_idx)
);


-- insert


insert into agent_groups (agent_group_id, agent_group_name, agent_group_description, active, reg_user_id, reg_date_time,
                          mod_user_id, mod_date_time)
values ('1', 'group1', 'description', true, 'SYSTEM', '2025-04-06 00:00:00', 'SYSTEM', '2025-04-06 01:00:00'),
       ('2', 'group2', 'description2', false, 'SYSTEM', '2025-04-06 00:00:00', 'SYSTEM', '2025-04-06 01:00:00');

insert into agent_groups_agents (agent_group_id, ip, user_name, order_idx)
values ('1', '127.0.0.1', 'user1', 0),
       ('1', '127.0.0.1', 'user2', 1),
       ('2', '127.0.0.2', 'user1', 0);

insert into jobs (job_id, active, job_description, job_name, job_type, period, script)
values ('1', true, 'jobDescription1', 'jobName1', 'SSH', '* * * * *', 'echo hello'),
       ('2', true, 'jobDescription2', 'jobName2', 'SSH', '1 * * * *', 'echo hello');


insert into jobs_target_agents (job_id, agent_group_id, ip, target_agent_type, user_name, order_idx)
values ('1', '1', null, 'GROUP', null, 0),
       ('1', null, '192.168.0.1', 'AGENT', 'user1', 1),
       ('2', null, '192.168.0.2', 'AGENT', 'user1', 0);

insert into job_executions (job_execution_id, job_id, job_execution_no, job_history_no,
                            job_status, execution_user_id, execution_date_time, start_date_time, end_date_time)
values ('1', '1', 1, 1, 'COMPLETED', 'SYSTEM', '2025-04-06 01:00:00', '2025-04-06 02:00:00', '2025-04-06 03:00:00'),
       ('2', '1', 2, 1, 'COMPLETED', 'SYSTEM', '2025-04-07 01:00:00', '2025-04-07 02:00:00', '2025-04-07 03:00:00'),
       ('3', '1', 3, 2, 'STOPPED', 'SYSTEM', '2025-04-08 01:00:00', '2025-04-08 02:00:00', '2025-04-08 03:00:00');


insert into job_executions_target_agents (job_execution_id, order_idx, ip, user_name, start_date_time, end_date_time, log)
values ('1', 0, '127.0.0.1', 'user1', '2025-04-06 01:00:00', '2025-04-06 02:00:00', null),
       ('1', 1, '127.0.0.1', 'user2', '2025-04-06 01:00:00', '2025-04-06 02:00:00', null),
       ('1', 2, '192.168.0.1', 'user1', '2025-04-06 01:00:00', '2025-04-06 02:00:00', null);

insert into job_history (job_id, job_history_no, job_name, job_type, history, reg_user_id, reg_date_time)
values ('1', 1, 'jobNameXXX', 'SSH', '{}', 'SYSTEM', '2025-04-06 01:00:00'),
       ('1', 2, 'jobName1', 'SSH', '{}', 'SYSTEM', '2025-04-06 01:00:00');
